pythonzhichan/DailyQuestion

question_1/aachen.md

question1 answer

---

.gitignore
question_1/heguilong.py

commit heguilong answer for question 1

commit heguilong answer for question 1

---

Ligda_answer_for_q1.md
question_1/Ligda.md

answer_for_question1

---

question_1/ralph.md

Ralph's answer for question_1

---

question_1/who.md

first question answer

---

question_1/xuehua.md

Xuehua's answer for 1st homework

Xuehua's answer for 1st homework

---

question_2/aachen.md

question2 answer

---

question_2/who.md

question 2 answer

---

question_2/minglin.py

question_2

---

question_2/guessnumber.py

XingDongZhe

---

question_2/DuCCNUer.md

增加第2个问题的回答(DuCCNUer)

---

question_2/guessNum.py

chenfeng's second answer:guess number

---

.idea/inspectionProfiles/profiles_settings.xml
question_1/linshizuowei.md
question_2/linshizuowei.md

question1,2

---

question_2/ralph_q2.md

Ralph's answer for question2

---

question_1/dongsheng_q1.py
test.py

q1提交     东升

---

question_3/who.py

question3 answer

---

question_3/ralph_q3.md

Ralph's answer for question3

---

question_3/chenfeng.py

commit statistic words

---

question_3/zen_of_python_03.py

Fix some bugs.

---

Fourth.py

the fourth question

---

rui/question2
rui/question3
rui/question4

create rui dictionary

---

question_4/ralph_q4.md

Ralph's answer for question 4

---

Paranoid-kid/zen_of_python_01.py
Paranoid-kid/zen_of_python_02.py
Paranoid-kid/zen_of_python_03.py
Paranoid-kid/zen_of_python_04.py
question_4/zen_of_python_04.py

change the structure of directory

add daily quesion 4

---

sunshiqi/question1.md
sunshiqi/question2.py
sunshiqi/question3.py
sunshiqi/question4.py

微信名IIXX作业目录更改

---

.gitignore

add ignore type in Django stuff

add ignore type in Django stuff

---

chenfeng/question5.py

commit question5

---

Sixth.py
Treehl/question6.py

The Sixth Question

---

totaljfb/Q5.py

Question 5, one last step to do:  parse the query_params and return a dictionary type object. Any suggestion is welcome

create my own .py for question 5

---

Godsing/question1.py
Godsing/question2.py
Godsing/question3.py
Godsing/question4.py
Godsing/question5.py
Godsing/question6.py
Godsing/test_for_question3.txt

公众号上看到您的活动，赶紧来参加，哈哈！作为初学者，花了一下午＋一晚上勉强现学现用，收获很多，很开心！终于体会到那句话：实践是最好的学习！感谢刘老师！

感谢刘老师，收获很多！

---

shuaidi/question01.py
shuaidi/question02.py

shuaidi's answer for question1.

shuaidi_answer_for_question1

---

totaljfb/Q1.py
totaljfb/Q2.py
totaljfb/Q5.py

finalized, should work for optional sections of the url like no fragment, no query parameters, etc.

q5.py finalized

---

koukekouke/question_6.py

add the count of multiline comments

debug and add function
